-- MySQL Script generated by MySQL Workbench
-- 06/17/16 09:52:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema app_cards
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema app_cards
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_cards` DEFAULT CHARACTER SET utf8 ;
USE `app_cards` ;

-- -----------------------------------------------------
-- Table `app_cards`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_cards`.`cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(64) NOT NULL,
  `subtitle` VARCHAR(64) NOT NULL,
  `text` VARCHAR(512) NULL,
  `cost` INT NOT NULL,
  `energy_type` INT NOT NULL,
  `max` INT NOT NULL,
  `die_id` INT NOT NULL,
  `set_id` INT NOT NULL,
  `collector_number` INT NOT NULL,
  `rarity` CHAR(1) NOT NULL,
  `text_global_id` INT NULL,
  `image_id` INT NULL,
  `affiliation_id` INT NOT NULL,
  `alliangment` CHAR(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_cards`.`globals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_cards`.`text_globals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_cards`.`sets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_cards`.`sets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `date` DATE NULL,
  `size` INT NULL,
  `legallity` CHAR(1) NULL,
  `image_id` INT NULL,
  `brand` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_cards`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_cards`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARBINARY(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_cards`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_cards`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_cards`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_cards`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `comment` VARCHAR(512) NOT NULL,
  `card_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_cards`.`dice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_cards`.`dice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `incolor` VARCHAR(45) NOT NULL,
  `outcolor` VARCHAR(45) NOT NULL,
  `face1` INT NOT NULL,
  `face2` INT NOT NULL,
  `face3` INT NOT NULL,
  `costface4` INT NOT NULL,
  `attackface4` INT NOT NULL,
  `deffenseface4` INT NOT NULL,
  `burstface4` INT NOT NULL,
  `costface5` INT NOT NULL,
  `attackface5` INT NOT NULL,
  `deffenseface5` INT NOT NULL,
  `burstface5` INT NOT NULL,
  `costface6` INT NOT NULL,
  `attackface6` INT NOT NULL,
  `deffenseface6` INT NOT NULL,
  `burstface6` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_cards`.`inventories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_cards`.`inventories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `card_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_cards`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_cards`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_cards`.`team_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_cards`.`team_cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `team_id` INT NOT NULL,
  `card_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_cards`.`affiliations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `app_cards`.`affiliations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `image_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
